### ISSUE TITLE
As an owner or logistics person, I want to edit existing product details, ensuring that the information remains up-to-date.

### ISSUE THREAD

**Issue by cookietriestoprogram** [cookietriestoprogram/abstrak#4]
Acceptance Criteria:

1. Given that I am logged in as an owner, when I navigate to an existing product's detail view, I should see an option to edit the product details.
2. Clicking the edit option should open a form pre-populated with the existing product information, including pictures, variations, stock levels, price, and manufacturing cost.
3. The edit form should allow updating all fields, including adding or removing pictures, changing variations, adjusting stock levels, and modifying price and manufacturing cost.
4. Upon submitting the form, the updated product details should be saved to the system, and I should receive a confirmation message.
5. If there is any invalid input or missing required information, the form should display appropriate error messages and highlight the problematic fields.
6. The changes should be immediately reflected in the product list and detail view upon successful submission.
7. Verify behavior when the edit form is submitted with incomplete information.
8. Validate the form's response to excessively large updated images.
9. Test the handling of invalid file formats for updated product images.
10. Test the form's functionality with special characters in updated product names or variations.
11. Evaluate the form's performance with a large number of variations.
12. Test the input validation for updated price and manufacturing cost fields.

![Image](https://github.com/cookietriestoprogram/abstrak/assets/96109976/5c6fe6ec-df8a-43e6-bd45-9648a0e769ad)

**Comment by cookietriestoprogram** [comment]
Frontend

- [ ] Design button to edit
- [ ] Design first part of the form
- [ ] Design the second part of the form


Backend

- [ ] Fetch the existing data
- [ ] Send the data to frontend to prefill
- [ ] Validate the edited data received
- [ ] Save the change

**Comment by mionemrct** [comment]
[BUG]

Frontend Issue: Edit Form's Next Button requires all fields to be edited to continue

How to reproduce the bug: Edit at least one field or edit none at all before clicking 'Next'

Severity: Medium

Priority: Medium

Screenshots: N/A

Expected behavior: The form should allow the user to continue to the next form [variations] even if not all fields from the previous are edited.

Actual behavior: The form does not allow the user to continue if none of the fields are changed or if the user did not change all fields.

Comments: N/A

**Comment by mionemrct** [comment]
[BUG]

Frontend Issue: Edit Form's Submit Button requires all fields to be edited to continue

How to reproduce the bug: Edit at least one field before clicking 'Submit'

Severity: Medium

Priority: Medium

Screenshots: N/A

Expected behavior: The form should allow the user to submit even if there is only one edited field.

Actual behavior: The form does not allow the user to submit if the user did not change all fields.

Comments: N/A

**Comment by mionemrct** [comment]
[BUG]

Frontend Issue: Edit Form's Next Button requires editing the image to continue.

Backend: Edit Form's Edit Picture does not update in the database.

How to reproduce the bug: Edit the image before clicking 'Submit'

Severity: Low

Priority: Medium

Screenshots: 

![Image](https://github.com/cookietriestoprogram/abstrak/assets/141164478/140c47e3-beba-459c-80b3-e92047f19a51)



Expected behavior: The form should allow the user to submit even if there is only one edited field and/or the image should at least be updated in the database.

Actual behavior: The form does not allow the user to submit if the user did not change all fields and when only the image is edited, it does not update in the database.

Comments: The site was open without being used for several minutes and this bug occurred. Even after restarting the site, port, and database, the bug continued to occur.

**Comment by cookietriestoprogram** [comment]
[SPRINT 2]
- [ ] Delete Variation
