### ISSUE TITLE
As an owner or logistics person, I want to add new products to the system by filling out a form that includes fields for pictures, variations, initial stock for each size, price, and manufacturing cost.

### ISSUE THREAD

**Issue by cookietriestoprogram** [cookietriestoprogram/abstrak#6]
Acceptance Criteria:

1. Given that I am logged in as an owner, when I navigate to the product creation form, I should see fields for adding product pictures, variations, initial stock for each variation, price, and manufacturing cost.
2. The product creation form should have a user-friendly interface with clearly labeled fields.
3. The form should allow the upload of multiple images for a single product.
4. The form should provide options for adding multiple variations (e.g., sizes, colors) with corresponding stock levels.
5. The price and manufacturing cost fields should accept only valid numerical inputs.
6. Upon submitting the form, the new product should be added to the system, and I should receive a confirmation message.
7. If there is any invalid input or missing required information, the form should display appropriate error messages and highlight the problematic fields.
8. The new product should be immediately available in the product list upon successful submission.
9. Ensure that the form handles the upload and storage of high-resolution images correctly.
10. Verify behavior when the form is submitted with incomplete information.
11. Test the handling of invalid file formats for product images.
12. Validate the form's response to excessively large images.
13. Test the form's functionality with special characters in product names or variations.
14. Validate data integrity and consistency after adding a new product

![Image](https://github.com/cookietriestoprogram/abstrak/assets/96109976/92ba7ef5-5516-4a94-9363-7105fbba8f6c)

**Comment by dlsrysju** [comment]
**Frontend Issue:** Submission Halted Despite Resolving 'Variation Must Be Unique' Error

**How to reproduce the bug:**
1. Attempt to submit a form with a variation that is not unique.
2. Receive the "Variation must be unique" error.
3. Correct the variation to make it unique.
4. Attempt to submit the form again.

**Severity**:  **Medium**:  It can cause inconvenience when the user encounters the error "Variation must be unique".

**Priority:** **Medium**: Although not critical, it's important to fix as it affects user experience and workflow.

**Screenshots**:
![Image](https://github.com/cookietriestoprogram/abstrak/assets/135517375/502144cc-bc0b-41e4-86f8-5e23f438c356)
![Image](https://github.com/cookietriestoprogram/abstrak/assets/135517375/66a31c3a-7d58-4513-b49e-bc980644833f)

**Expected behavior:** After correcting the error and resubmitting the form, the submission should proceed successfully.

**Actual behavior:** Despite fixing the error of "Variation unique", the form submission is still blocked by the previous error message, preventing the user from proceeding.

**Comments:** N/A

**Comment by dlsrysju** [comment]
[BUG]

**Frontend Issue:** Form Submission Allows Invalid File Formats (PDF & Word)

**How to reproduce the bug:**

1. Attempt to submit a form with PDF or Word files uploaded as attachments.

**Severity:**  Low

**Priority:** Medium

**Screenshots**: N/A

**Expected behavior**: The form should prevent submission if invalid file formats (PDF & Word) are uploaded.

**Actual behavior**: The form proceeds with submission despite invalid file formats (PDF & Word) being uploaded.

**Comments:** N/A

**Comment by dlsrysju** [comment]
[BUG]

Frontend Issue: Form Submission Allows Negative Input from Price

How to reproduce the bug:

1.  Attempt to use negative values in price
2. All fields must be filled
3. Click Next

Severity: Low

Priority: Medium

Screenshots: 

![Image](https://github.com/cookietriestoprogram/abstrak/assets/135517375/deb589c3-6a15-4f3c-a98a-5e97934b282f)


Expected behavior: The form should prevent submission if the price input contains negative value

Actual behavior: The form proceeds even if the price input is negative.

Comments: N/A

**Comment by dlsrysju** [comment]
[BUG]

Frontend Issue: Form Submission Allows Manufacturing Cost to be Missing

How to reproduce the bug:
1. Attempt filling in the 'Variation Name' and 'Stock' and leave 'Manufacturing Cost' blank 
2. Click the submit

Severity: Medium: The user might still oversight the missing field and proceeds with submission.

Priority: Medium

Screenshots:


![Image](https://github.com/cookietriestoprogram/abstrak/assets/135517375/8c387cb0-a765-4b39-a91d-5d8d58b2c3c1)


Expected behavior: The form should prevent submission if the 'Manufacturing Cost' is empty

Actual behavior: The form proceeds even if the 'Manufacturing Cost' is empty.

Comments: N/A

**Comment by pngnyume** [comment]
@cookietriestoprogram 
[Sprint 2] Revisions:
- [ ] Delete Variation
